{% set name = "spectrapepper" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef2650beba18c5bda3c76608e6eeeb102d49f4c404ad010f7a3a854fde306a84

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - spectrapepper

about:
  home: https://github.com/enricgrau/spectrapepper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to simplify and accelerate analysis of spectroscopy data
  doc_url: https://enricgrau.github.io/spectrapepper/
  dev_url: https://github.com/enricgrau/spectrapepper

extra:
  recipe-maintainers:
    - enricgrau
