{% set name = "spectrapepper" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7f3862d1bf24a89453bc08eb9e3c6b1a808bfe8b3be08a483c9f3631ad003850

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - spectrapepper

about:
  home: https://github.com/spectrapepper/spectrapepper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to simplify and accelerate analysis of spectroscopy data
  doc_url: https://spectrapepper.github.io/spectrapepper/
  dev_url: https://github.com/spectrapepper/spectrapepper

extra:
  recipe-maintainers:
    - enricgrau
